config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only:[:index, :show] do
    resources :buddy_sheets do
      resources :buddy_study_logs, only: [:update]
    end
  end

  resources :day_offs
  

  root 'users#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/buddy_sheet.rb
class BuddySheet < ApplicationRecord
  belongs_to :user
  has_many :buddy_study_logs
  
  def dayoff_diff
    total_diff = 0
    das = dayoffs
    (start_at..start_at.since(period.days)).each do |day|
      if das.include?(day)
         total_diff += 1
      end
    end
    return total_diff
  end

  def total_period
    total_diff = dayoff_diff
    return (start_at..start_at.since((period + total_diff - 1).days))
  end

  def dayoffs
    DayOff.pluck(:off_plan)
  end

  def create_buddy_study_logs
    total_period.each do |day|
      if dayoffs.include?(day)
        next
      end
      buddy_study_logs.create(schedule_date: day, result_date: day)
    end    
  end

end

app/models/buddy_study_log.rb
class BuddyStudyLog < ApplicationRecord
  belongs_to :buddy_sheet
end

app/models/day_off.rb
class DayOff < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_one :buddy_sheet

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/buddy_sheets_controller.rb
class BuddySheetsController < ApplicationController
  before_action :set_buddy_sheet, only: [:show, :edit, :update, :destroy]
  before_action :set_user, only: [:show, :edit, :new]
  # GET /buddy_sheets
  # GET /buddy_sheets.json
  def index
    @buddy_sheets = BuddySheet.all
  end

  # GET /buddy_sheets/1
  # GET /buddy_sheets/1.json
  def show
  end

  # GET /buddy_sheets/new
  def new
    @buddy_sheet = BuddySheet.new
  end

  # GET /buddy_sheets/1/edit
  def edit
  end

  # POST /buddy_sheets
  # POST /buddy_sheets.json
  def create
      user_id = params[:user_id]
      @buddy_sheet = BuddySheet.new(buddy_sheet_params)
      @buddy_sheet.user_id = user_id
      respond_to do |format|
        if current_user.buddy_sheet.blank? && @buddy_sheet.save
          @buddy_sheet.create_buddy_study_logs
          format.html { redirect_to user_buddy_sheet_path(user_id: user_id, id: @buddy_sheet), notice: 'Buddy sheet was successfully created.' }
          format.json { render :show, status: :created, location: @buddy_sheet }
        else
          format.html { render :new }
          format.json { render json: @buddy_sheet.errors, status: :unprocessable_entity }
        end
      end
    end

  # PATCH/PUT /buddy_sheets/1
  # PATCH/PUT /buddy_sheets/1.json
  def update
    respond_to do |format|
      if @buddy_sheet.update(buddy_sheet_params)
        format.html { redirect_to user_buddy_sheet(user_id: user_id, id: @buddy_sheet), notice: 'Buddy sheet was successfully updated.' }
        format.json { render :show, status: :ok, location: @buddy_sheet }
      else
        format.html { render :edit }
        format.json { render json: @buddy_sheet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /buddy_sheets/1
  # DELETE /buddy_sheets/1.json
  def destroy
    @buddy_sheet.destroy
    respond_to do |format|
      format.html { redirect_to user_path(1), notice: 'Buddy sheet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_user
      @user = User.find(params[:user_id])
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_buddy_sheet
      @buddy_sheet = BuddySheet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def buddy_sheet_params
      params.require(:buddy_sheet).permit(:start_at, :period, :long_target, :short_target)
    end
end

app/controllers/buddy_study_logs_controller.rb
class BuddyStudyLogsController < ApplicationController
  def update
    @buddy_study_log = BuddyStudyLog.find(params[:id])
    @buddy_study_log.update(study_log_params)
    redirect_to user_buddy_sheet_path(user_id: params[:user_id], id: params[:buddy_sheet_id])
  end

  # def update_study_result
    
  # end

  # def update_trainer_comment
    
  # end

  private
  def study_log_params
    params.require(:buddy_study_log).permit(:schedule_date, :schedule_time, :schedule_place, :result_date, :result_time, :result_place, :trainer_comment, :schedule_content, :result_content, :thought)
  end
end

app/controllers/day_offs_controller.rb
class DayOffsController < ApplicationController
  before_action :set_day_off, only: [:show, :edit, :update, :destroy]

  # GET /day_offs
  # GET /day_offs.json
  def index
    @day_offs = DayOff.all
  end

  # GET /day_offs/1
  # GET /day_offs/1.json
  def show
  end

  # GET /day_offs/new
  def new
    @day_off = DayOff.new
  end

  # GET /day_offs/1/edit
  def edit
  end

  # POST /day_offs
  # POST /day_offs.json
  def create
    @day_off = DayOff.new(day_off_params)

    respond_to do |format|
      if @day_off.save
        format.html { redirect_to @day_off, notice: 'Day off was successfully created.' }
        format.json { render :show, status: :created, location: @day_off }
      else
        format.html { render :new }
        format.json { render json: @day_off.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /day_offs/1
  # PATCH/PUT /day_offs/1.json
  def update
    respond_to do |format|
      if @day_off.update(day_off_params)
        format.html { redirect_to @day_off, notice: 'Day off was successfully updated.' }
        format.json { render :show, status: :ok, location: @day_off }
      else
        format.html { render :edit }
        format.json { render json: @day_off.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /day_offs/1
  # DELETE /day_offs/1.json
  def destroy
    @day_off.destroy
    respond_to do |format|
      format.html { redirect_to day_offs_url, notice: 'Day off was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_day_off
      @day_off = DayOff.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def day_off_params
      params.require(:day_off).permit(:off_plan)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @dayoffs = DayOff.pluck(:off_plan)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/buddy_sheets_helper.rb
module BuddySheetsHelper
end

app/helpers/buddy_study_logs_helper.rb
module BuddyStudyLogsHelper
end

app/helpers/day_offs_helper.rb
module DayOffsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/buddy_sheets/_form.html.erb
<%= form_for(buddy_sheet, url: user_buddy_sheets_path(@user)) do |f| %>
  <% if buddy_sheet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(buddy_sheet.errors.count, "error") %> prohibited this buddy_sheet from being saved:</h2>

      <ul>
      <% buddy_sheet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :start_at, "開始日" %>
    <%= f.date_select :start_at %>
  </div>

  <div class="field">
    <%= f.label :period, "期間" %>
    <%= f.number_field :period %>
  </div>

  <div class="field">
    <%= f.label :long_target, "長期目標" %>
    <%= f.text_area :long_target %>
  </div>
  <div class="field">
    <%= f.label :short_target, "短期目標" %>
    <%= f.text_area :short_target %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/buddy_sheets/edit.html.erb
<h1>Editing Buddy Sheet</h1>

<%= render 'form', buddy_sheet: @buddy_sheet %>

<%= link_to 'Show', @buddy_sheet %> |
<%= link_to 'Back', buddy_sheets_path %>

app/views/buddy_sheets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Buddy Sheets</h1>

<table>
  <thead>
    <tr>
      <th>Start at</th>
      <th>Period</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @buddy_sheets.each do |buddy_sheet| %>
      <tr>
        <td><%= buddy_sheet.start_at %></td>
        <td><%= buddy_sheet.period %></td>
        <td><%= link_to 'Show', buddy_sheet %></td>
        <td><%= link_to 'Edit', edit_buddy_sheet_path(buddy_sheet) %></td>
        <td><%= link_to 'Destroy', buddy_sheet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Buddy Sheet', new_buddy_sheet_path %>

app/views/buddy_sheets/new.html.erb
<h1>New Buddy Sheet</h1>

<%= render 'form', buddy_sheet: @buddy_sheet %>

<%= link_to 'Back', users_path %>

app/views/buddy_sheets/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @user.email %>のバディシート</h1>


<div class="target-container">
  <h2>目標</h2>
  <div class="target-content">
    <div class="long-target">
      長期： <%= @buddy_sheet.long_target %>
    </div>
    <div class="short-target">
      短期： <%= @buddy_sheet.short_target %>
    </div>
  </div>
</div>

<% 
  num = 0
  time = [0]
  24.times { 
    num += 0.5
    time << num
   }
   study_places = %w(教室 オンライン)
   study_contents = %w(Webサイト制作Lv1 Webサイト制作Lv2 Webサイト制作Lv3 Webサイト制作Lv4 WebアプリケーションLv1 WebアプリケーションLv2 WebアプリケーションLv3 WebアプリケーションLv4)
 %>

<table id="buddy-study-table">
  <thead class="">
    <tr>
      <th scope="cols" rowspan="2">学習期間</th>
      <th scope="cols" colspan="4">予定</th>
      <th scope="cols" rowspan="2"></th>
      <th scope="cols" colspan="4">実績</th>
      <th scope="cols" rowspan="2">感想</th>
      <th scope="cols" rowspan="2"></th>
      <th scope="cols" rowspan="2">コメント</th>
      <th scope="cols" rowspan="2"></th>
    </tr>
    <tr>
      <th scope="cols">日付</th>
      <th scope="cols">時間</th>
      <th scope="cols">場所</th>
      <th scope="cols">内容</th>

      <th scope="cols">日付</th>
      <th scope="cols">時間</th>
      <th scope="cols">場所</th>     <th scope="cols">内容</th>

    </tr>
  </thead>
  <tbody class="">
    <% @buddy_sheet.buddy_study_logs.each_with_index do |log, i| %>
       <tr class="study-log">
        <!-- 学習期間 -->
        <th scope="cols"><%= i + 1 %>日目</th>
        <!-- 予定 -->
        <th scope="cols"><%= log.schedule_date.strftime("%m / %d") %></th>
        <th scope="cols" class="schedule_element"><%= log.schedule_time %></th>
        <th scope="cols" class="schedule_element"><%= log.schedule_place %></th>
        <th scope="cols" class="schedule_element"><%= log.schedule_content %></th>
        <!-- 予定編集フォーム -->
        <%= form_for(log, url: user_buddy_sheet_buddy_study_log_path(user_id: @user, buddy_sheet_id: @buddy_sheet, id: log)) do |f| %>
          <th scope="cols" class="schedule_edit_form"><%= f.select :schedule_time, time %></th>
          <th scope="cols" class="schedule_edit_form"><%= f.select :schedule_place, study_places %></th>
          <th scope="cols" class="schedule_edit_form"><%= f.select :schedule_content, study_contents %></th>
          <th scope="cols" class="schedule_edit_form"><%= f.submit "更新", class: "edit_btn" %></th>
        <% end %>
        <th class="study_schedule_edit_btn schedule_element"><div class="edit_btn">編集</div></th>
        <!-- 実績 -->
        <th scope="cols"><%= log.result_date.strftime("%m / %d") %></th>
        <th scope="cols" class="result_element"><%= log.result_time %></th>
        <th scope="cols" class="result_element"><%= log.result_place %></th>
        <th scope="cols" class="result_element"><%= log.result_content %></th>
        <!-- 実績編集フォーム -->
        <%= form_for(log, url: user_buddy_sheet_buddy_study_log_path(user_id: @user, buddy_sheet_id: @buddy_sheet, id: log)) do |f| %>
          <th scope="cols" class="result_edit_form"><%= f.select :result_time, time %></th>
          <th scope="cols" class="result_edit_form"><%= f.select :result_place, study_places %></th>
          <th scope="cols" class="result_edit_form"><%= f.select :result_content, study_contents %></th>
          <th class="result_edit_form"><%= f.text_area :thought %></th>
          <th class="result_edit_form "><%= f.submit "更新", class: "edit_btn" %></th>

        <% end %>
        <!-- 感想 -->
        <th scope="cols" width="150" class="result_element"><%= log.thought %></th>
        <th class="study_result_edit_btn result_element"><div class="edit_btn">編集</div></th>
        <!-- コメント -->
        <th scope="cols" width="150" class="comment_element"><%= log.trainer_comment %></th>
        <th class="comment_edit_btn comment_element"><div class="edit_btn">コメント</div></th>
        <!-- コメントフォーム -->
        <%= form_for(log, url: user_buddy_sheet_buddy_study_log_path(user_id: @user, buddy_sheet_id: @buddy_sheet, id: log)) do |f| %>
          <th class="comment_edit_form"><%= f.text_area :trainer_comment %></th>
          <th class="comment_edit_form"><%= f.submit "コメント", class: "edit_btn" %> <div class="comment_edit_btn edit_btn">-</div></th>
        <% end %>
      </tr>
    <% end %>
   
  </tbody>
</table>

<script>
  $(".study_schedule_edit_btn").click(function(){
    var schedule_element = $(this).parents(".study-log").find(".schedule_element");
    var schedule_edit_form = $(this).parents(".study-log").find(".schedule_edit_form");
    // console.log(schedule_edit_form);
    if (schedule_element.is(':visible')) {
      schedule_element.hide();
      schedule_edit_form.show();
    } else {
      schedule_element.show();
      schedule_edit_form.hide();
    }
  });

  $(".study_result_edit_btn").click(function(){
    var result_element = $(this).parents(".study-log").find(".result_element");
    var result_edit_form = $(this).parents(".study-log").find(".result_edit_form");
    // console.log(schedule_edit_form);
    if (result_element.is(':visible')) {
      result_element.hide();
      result_edit_form.show();
    } else {
      result_element.show();
      result_edit_form.hide();
    }
  });

  $(".comment_edit_btn").click(function(){
    var comment_element = $(this).parents(".study-log").find(".comment_element");
    var comment_edit_form = $(this).parents(".study-log").find(".comment_edit_form")
    if (comment_element.is(':visible')) {
      comment_element.hide();
      comment_edit_form.show();
    } else {
      comment_element.show();
      comment_edit_form.hide();
    }
  });
</script>

app/views/day_offs/_form.html.erb
<%= form_for(day_off) do |f| %>
  <% if day_off.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(day_off.errors.count, "error") %> prohibited this day_off from being saved:</h2>

      <ul>
      <% day_off.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :off_plan %>
    <%= f.date_select :off_plan %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/day_offs/edit.html.erb
<h1>Editing Day Off</h1>

<%= render 'form', day_off: @day_off %>

<%= link_to 'Show', @day_off %> |
<%= link_to 'Back', day_offs_path %>

app/views/day_offs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Day Offs</h1>

<table>
  <thead>
    <tr>
      <th>Off plan</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @day_offs.each do |day_off| %>
      <tr>
        <td><%= day_off.off_plan %></td>
        <td><%= link_to 'Show', day_off %></td>
        <td><%= link_to 'Edit', edit_day_off_path(day_off) %></td>
        <td><%= link_to 'Destroy', day_off, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Day Off', new_day_off_path %>

app/views/day_offs/new.html.erb
<h1>New Day Off</h1>

<%= render 'form', day_off: @day_off %>

<%= link_to 'Back', day_offs_path %>

app/views/day_offs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Off plan:</strong>
  <%= @day_off.off_plan %>
</p>

<%= link_to 'Edit', edit_day_off_path(@day_off) %> |
<%= link_to 'Back', day_offs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BuddySample</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= link_to '休みの日登録', new_day_off_path %>
    <%= yield %>
  </body>
</html>

app/views/users/index.html.erb
<%= link_to "ログアウト", destroy_user_session_path, method: :delete %>

<h1>User#index</h1>
<% @users.each do |user| %>
  <div><%= link_to user.email, user_path(user) %></div>
<% end %>

app/views/users/show.html.erb
<h1>User#show</h1>

<% if @user.buddy_sheet.present? %>
  <%= link_to "バディシート編集", edit_user_buddy_sheet_path(user_id: @user.id, id: @user.buddy_sheet.id) %>
<% end %>

<%= link_to "バディシート作る", new_user_buddy_sheet_path(@user) %>